# Generated by Django 3.2.9 on 2021-11-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='Profile_Pic',
            new_name='profile_pic',
        ),
    ]
