# Generated by Django 3.2.9 on 2021-12-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20211215_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
